export const COCKTAILS_UPDATE_LIST = 'COCKTAILS_UPDATE_LIST'
export const COCKTAILS_UPDATE_FETCHING = 'COCKTAILS_UPDATE_FETCHING'
export const COCKTAILS_UPDATE_SELECTED = 'COCKTAILS_UPDATE_SELECTED'
export const COCKTAIL_UPDATE_DETAIL = 'COCKTAIL_UPDATE_DETAIL'
